### ISSUE TITLE
Page hierarchy

### ISSUE THREAD

**Issue by eriktelepovsky** [bartTC/django-wakawaka#15]
Hi. Nice library.

Is it possible to create a page hierarchy or a tree structure? Like a nested navigation in a website.

**Comment by bartTC** [comment]
There is the page list which ... lists all pages. But generally these Wiki pages are flat. You build structure by their name, e.g. `Family` and `Family/Jon` as their name.

**Comment by eriktelepovsky** [comment]
I see. Have you considered using django-mptt for this functionality?

**Comment by bartTC** [comment]
No, there's no intention to build anything like this. Wikis are flat and it's structure is content driven.
