### ISSUE TITLE
wakawaka_tags.py does not support multiple wikiwords with the same name in pinax

### ISSUE THREAD

**Issue by jakesrt8** [bartTC/django-wakawaka#3]
The look up for the page should be different when the group is not None:

New version of wakawaka_tags.py replace_wikiwords:

from django.contrib.contenttypes.models import ContentType

def replace_wikiwords(value, group=None):

    def replace_wikiword(m):
        slug = m.group(1)

        try:
            kwargs = {
                'slug': slug,
            }
            if group:
                ct = ContentType.objects.get_for_model(group.__class__)
                page = WikiPage.objects.get(slug=slug,content_type=ct,object_id=group.id)
                url = group.content_bridge.reverse('wakawaka_page', group, kwargs=kwargs)
            else:
                page = WikiPage.objects.get(slug=slug)
                url = reverse('wakawaka_page', kwargs=kwargs)
            return r'<a href="%s">%s</a>' % (url, slug)
        except ObjectDoesNotExist:
            kwargs = {
                'slug': slug,
            }
            if group:
                url = group.content_bridge.reverse('wakawaka_edit', group, kwargs=kwargs)
            else:
                url = reverse('wakawaka_edit', kwargs=kwargs)
            return r'<a class="doesnotexist" href="%s">%s</a>' % (url, slug)
    return mark_safe(WIKI_WORDS_REGEX.sub(replace_wikiword, value))

Old version:

def replace_wikiwords(value, group=None):
    def replace_wikiword(m):
        slug = m.group(1)
        try:
            page = WikiPage.objects.get(slug=slug)
            kwargs = {
                'slug': slug,
            }
            if group:
                url = group.content_bridge.reverse('wakawaka_page', group, kwargs=kwargs)
            else:
                url = reverse('wakawaka_page', kwargs=kwargs)
            return r'<a href="%s">%s</a>' % (url, slug)
        except ObjectDoesNotExist:
            kwargs = {
                'slug': slug,
            }
            if group:
                url = group.content_bridge.reverse('wakawaka_edit', group, kwargs=kwargs)
            else:
                url = reverse('wakawaka_edit', kwargs=kwargs)
            return r'<a class="doesnotexist" href="%s">%s</a>' % (url, slug)
    return mark_safe(WIKI_WORDS_REGEX.sub(replace_wikiword, value))

**Comment by bartTC** [comment]
Pinax support has been removed.
