### ISSUE TITLE
Column 'creator_ip' cannot be null

### ISSUE THREAD

**Issue by geweb7** [bartTC/django-wakawaka#34]
freshly installed
submit on /wiki/WikiIndex/edit/ 
raises
django.db.utils.IntegrityError: (1048, "Column 'creator_ip' cannot be null")

django 5.0.6
django-wakawaka1.4

**Comment by bartTC** [comment]
The IP Address is obtained from this http header: https://github.com/bartTC/django-wakawaka/blob/main/wakawaka/forms.py#L32 

Can you describe your envrionment a bit more so I can replicate it?

**Comment by geweb7** [comment]
no idea why it's not accessible

i have nginx and gunicorn and rather standart django project, no custom middleware.

i'm not sure if vpn on my laptop matters

**Comment by bartTC** [comment]
This has been fixed in v1.5. The field is now optional.
